# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

categories = Category.create!([{ title: 'Programming' }, { title: 'Auto' },
                               { title: 'Music' }, { title: 'Movies' }])

users = User.create!([{ username: 'Luke', email: 'luck@rebel.mail' },
                      { username: 'Han', email: 'han@smuggler.mail' },
                      { username: 'Lea', email: 'lea@rebel.mail' },
                      { username: 'Lando', email: 'lando@cloud.city' }])

tests = Test.create!([{ title: 'HTML', category: categories[0], level: 0, author: users[0] },
                      { title: 'Ruby', category: categories[0], level: 1, author: users[0] },
                      { title: 'RoR', category: categories[0], level: 1, author: users[0] },
                      { title: 'Manufacturers', category: categories[1], level: 0, author: users[1] },
                      { title: 'Autosport', category: categories[1], level: 2, author: users[1] },
                      { title: 'Music history', category: categories[2], level: 2, author: users[2] },
                      { title: 'Musical instruments', category: categories[2], level: 1, author: users[2] },
                      { title: 'Movies history', category: categories[3], level: 1, author: users[3] },
                      { title: 'Actors', category: categories[3], level: 0, author: users[3] }])

questions = Question.create!([{ body: 'What abbreviation HTML means?', test: tests[0] },
                              { body: "Who is 'Matz'?", test: tests[1] },
                              { body: 'When ruby language was created?', test: tests[1] },
                              { body: 'What is Rails?', test: tests[2] },
                              { body: 'Who created Rails?', test: tests[2] },
                              { body: 'Which tag used for a paragraph?', test: tests[0] },
                              { body: 'What tag <a> for?', test: tests[0] },
                              { body: 'In which city BMW is located?', test: tests[3] },
                              { body: 'Which F1 team is most successful?', test: tests[4] },
                              { body: 'Most powerful road legal car in the world?', test: tests[3] },
                              { body: 'Fastest F1 pit stop', test: tests[4] },
                              { body: 'Longest circuit?', test: tests[4] },
                              { body: 'Largest music festival', test: tests[5] },
                              { body: 'Band who released the most studio albums', test: tests[5] },
                              { body: 'Loudest musical instrument', test: tests[6] },
                              { body: 'Which instrument has the most strings', test: tests[6] },
                              { body: 'First color movie was created in?', test: tests[7] },
                              { body: 'Who was the first movie star', test: tests[7] },
                              { body: 'First Johnny Depp movie', test: tests[8] },
                              { body: "Hollywood actors who've appeared in the most movies", test: tests[8] }])

answers = Answer.create!([{ body: 'HyperText Markup Language', question: questions[0], correct: true },
                          { body: 'Hierarchy Transfer Method Language', question: questions[0], correct: false },
                          { body: 'Handsome Tag Markup Language', question: questions[0], correct: false },
                          { body: 'Matz Mikkelsen, Hollywood actor', question: questions[1], correct: false },
                          { body: 'Yukihiro Matsumoto, Ruby language creator', question: questions[1], correct: true },
                          { body: 'Steven Matz, MLB player', question: questions[1], correct: false },
                          { body: '1995', question: questions[2], correct: true },
                          { body: '1993', question: questions[2], correct: false },
                          { body: '1996', question: questions[2], correct: false },
                          { body: 'A web-application framework', question: questions[3], correct: true },
                          { body: 'A programming language', question: questions[3], correct: false },
                          { body: 'A web-site generator tool', question: questions[3], correct: false },
                          { body: 'David Heinemeier Hansson', question: questions[4], correct: true },
                          { body: 'Yukihiro Matsumoto', question: questions[4], correct: false },
                          { body: 'Daniel Kaufman', question: questions[4], correct: false },
                          { body: '<p> tag', question: questions[5], correct: true },
                          { body: '<article> tag', question: questions[5], correct: false },
                          { body: '<quote> tag', question: questions[5], correct: false },
                          { body: 'New line', question: questions[6], correct: false },
                          { body: 'Comment', question: questions[6], correct: false },
                          { body: 'Link', question: questions[6], correct: true },
                          { body: 'München', question: questions[7], correct: true },
                          { body: 'Berlin', question: questions[7], correct: false },
                          { body: 'Köln', question: questions[7], correct: false },
                          { body: 'McLaren', question: questions[8], correct: false },
                          { body: 'Ferrari', question: questions[8], correct: true },
                          { body: 'Red Bull', question: questions[8], correct: false },
                          { body: 'Ferrari SF90 Stradale', question: questions[9], correct: false },
                          { body: 'Pininfarina Battista', question: questions[9], correct: true },
                          { body: 'Bugatti Chiron', question: questions[9], correct: false },
                          { body: 'Less than 3 seconds', question: questions[10], correct: false },
                          { body: 'Less than 5 seconds', question: questions[10], correct: false },
                          { body: 'Less than 5 seconds', question: questions[10], correct: true },
                          { body: 'Suzuka Circuit', question: questions[11], correct: false },
                          { body: 'Silverstone', question: questions[11], correct: false },
                          { body: 'Nürburgring', question: questions[11], correct: true },
                          { body: 'Summerfest', question: questions[12], correct: false },
                          { body: 'Mawazine', question: questions[12], correct: true },
                          { body: 'Rock in Rio', question: questions[12], correct: false },
                          { body: 'The Rolling Stones', question: questions[13], correct: false },
                          { body: 'Hawkwind', question: questions[13], correct: true },
                          { body: 'Motörhead', question: questions[13], correct: false },
                          { body: 'Trombone', question: questions[14], correct: false },
                          { body: 'Violin', question: questions[14], correct: false },
                          { body: 'Organ', question: questions[14], correct: true },
                          { body: 'Double bass', question: questions[15], correct: false },
                          { body: 'Piano', question: questions[15], correct: true },
                          { body: 'Harp', question: questions[15], correct: false },
                          { body: '1935', question: questions[16], correct: true },
                          { body: '1931', question: questions[16], correct: false },
                          { body: '1946', question: questions[16], correct: false },
                          { body: 'Charles Chaplin', question: questions[17], correct: false },
                          { body: 'Mary Pickford', question: questions[17], correct: false },
                          { body: 'Florence Annie Bridgwood', question: questions[17], correct: true },
                          { body: 'A Nightmare on Elm Street', question: questions[18], correct: true },
                          { body: 'Platoon', question: questions[18], correct: false },
                          { body: 'Edward Scissorhands', question: questions[18], correct: false },
                          { body: 'Michael Caine', question: questions[19], correct: true },
                          { body: 'Anthony Hopkins', question: questions[19], correct: false },
                          { body: 'Samuel L. Jackson', question: questions[19], correct: false }])

UserTest.create!([{ user: users[0], test: tests[0] },
                  { user: users[0], test: tests[1] },
                  { user: users[0], test: tests[2] },
                  { user: users[1], test: tests[1] },
                  { user: users[2], test: tests[1] },
                  { user: users[2], test: tests[5] },
                  { user: users[2], test: tests[6] },
                  { user: users[3], test: tests[1] },
                  { user: users[3], test: tests[7] }])

